apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\docker\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\docker\kompose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: JDBC_DRIVER
          value: com.mysql.jdbc.Driver
        - name: JDBC_PASS
          value: bmcAdm1n
        - name: JDBC_URL
          value: jdbc:mysql://mysql/jpetstore
        - name: JDBC_USER
          value: root
        image: juananmora/jpetk8s
        imagePullPolicy: ""
        name: tomcatcompose
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
