apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\docker\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "8011"
    port: 8011
    targetPort: 8080
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
